### ISSUE TITLE
Correction in cart.html File Access Issue

### ISSUE THREAD

**Issue by MuditGoel15** [MuditGoel15/SCM_Final_Evaluation#14]
regarding the difficulty you've experienced accessing the cart.html file. It seems there's a correction required in the code to rectify this issue. Kindly implement the outlined correction to ensure seamless access to the cart.html file.

**Comment by 0077mukund** [comment]
Okay I will resolve the problem as soon as possible

**Comment by 0077mukund** [comment]
I have resolve the issue you can check it out.

**Comment by MuditGoel15** [comment]
The issue has been resolved
