### ISSUE TITLE
Pizza Image Not Displaying in pizza.html File

### ISSUE THREAD

**Issue by MuditGoel15** [MuditGoel15/SCM_Final_Evaluation#6]
Upon inspecting the code and conducting some troubleshooting, it appears that there might be an error either in the image source path or in the code referencing the image.To ensure the seamless functionality and visual appeal of our website, it is imperative to address this issue promptly. I kindly request your assistance in investigating the root cause of the problem and implementing the necessary corrective measures.

**Comment by muskan5091** [comment]
Okay I will try to resolve the problem as soon as possible.

**Comment by muskan5091** [comment]
I have resolved the issue of the pizza image you can check it out.

**Comment by MuditGoel15** [comment]
Issue have been resolved
